#!/bin/bash
set -x
name=$(sed -n 's,Name=,,p' /etc/tinc/gone/tinc.conf)
if_ip=$(sed -n 's,Subnet=,,p' /etc/tinc/gone/hosts/${name})
ns_name="vpn_fr"

echo ${if_ip}

sudo systemctl restart tinc@gone
sleep 1
sudo ip netns add ${ns_name}
sudo ip link set dev gone netns ${ns_name}
sudo ip netns exec ${ns_name} ip link set dev gone up
sudo ip netns exec ${ns_name} ip a add ${if_ip} dev gone
sudo ip netns exec ${ns_name} ip r add 192.168.135.0/24 dev gone
sudo ip netns exec ${ns_name} ip r add default via 192.168.135.8 dev gone
# Not sure why this is mendatory
sudo ip netns exec ${ns_name} ifconfig gone mtu 1300
sudo ip netns exec ${ns_name} sysctl net.ipv6.conf.all.disable_ipv6=1
sudo mkdir -p /etc/netns/${ns_name}
sudo bash -c "echo 'nameserver 8.8.8.8' > /etc/netns/${ns_name}/resolv.conf"
sudo -E ip netns exec ${ns_name} su $USER -c "google-chrome --user-data-dir=$HOME/.config/chrome-vpn-fr"
